### ISSUE TITLE
Make tools permanent

### ISSUE THREAD

**Issue by IamViditAgarwal** [genepattern/nbtools#1]
Hi , I am using the nbtools framework . I want to ask a couple of things like : 
1) The tools I create are temporary. When I open the notebook again they disappear. So can u tell me a way to make them permanent ?
2) I want to ship some tools default when the user opens the notebook, default tools should be available .. How can I achieve this?

PS: Thanks in advance
Vdiit

**Comment by tmtabor** [comment]
I'm currently working on a way to define tools via a JSON file that can be embedded in a notebook's metadata or saved as a separate file, but this functionality isn't fully implemented yet.

For now, the easiest way to automatically load the tools when opening the notebook would be to put their definition in a cell with a UI Builder widget. This cell will be executed automatically when the notebook is loaded. The code would be something like:

```python
import nbtools

@nbtools.build_ui
def load_tools:
    """
    This cell will be executed when the notebook is opened and a widget will be rendered.
    """
    print('Tools are loaded')
```

**Comment by IamViditAgarwal** [comment]
> I'm currently working on a way to define tools via a JSON file that can be embedded in a notebook's metadata or saved as a separate file, but this functionality isn't fully implemented yet.
> 
> For now, the easiest way to automatically load the tools when opening the notebook would be to put their definition in a cell with a UI Builder widget. This cell will be executed automatically when the notebook is loaded. The code would be something like:
> 
> ```python
> import nbtools
> 
> @nbtools.build_ui
> def load_tools:
>     """
>     This cell will be executed when the notebook is opened and a widget will be rendered.
>     """
>     print('Tools are loaded')
> ```

Can we build tools using Js ,, As in the doc only python3 method is given to build tools ?
I guess using Js can solve issue to some extend

**Comment by tmtabor** [comment]
Tools can also be built in Javascript, for example:

```javascript
// Import nbtools using RequireJS
require(["nbtools"], function(nbtools) {

    // Instantiate the NBTool object with necessary metadata
    const hello_tool = new nbtools.NBTool({
        id: 'hello_tool',
        name: 'Hello World Tool',
        origin: 'Notebook',

        load: function() {},  // Called when registered

        render: function() {  // Called when the tool is selected
            const cell = Jupyter.notebook.get_selected_cell();
            cell.set_text('Hello World');
        }
    });

    // Register the tool
    nbtools.instance().register(hello_tool);
});
```

[The full documentation is here.](https://github.com/genepattern/nbtools/blob/master/doc/toolmanager.md)

**Comment by IamViditAgarwal** [comment]
I am using python code for file uploader in nbtools like this
```
def file_up() :
    @nbtools.build_ui(parameters={
    "param_1": {
        "type": "file",
        "kinds": ["csv" , ".txt"]
        }
    })

    def file_upload(param_1):
        #print(param_1)
        return 'file is uploaded'
```
and calling `file_up()` .
When I call the file_up() function , file_uploader generates but as soon as I run the widget after uploading the file in it , gets the error `file_upload() is not defined`  ..

file_upload() is the function that I have defined above in  code. 

PS : Can u help me to figure out this error
Thanks in advance
Vidit

**Comment by tmtabor** [comment]
Try this code:

```python
import nbtools

@nbtools.build_ui(parameters={
    "param_1": {
        "type": "file",
        "kinds": ["csv" , ".txt"]
        }
    })
def file_up(param_1) :
    return 'file is uploaded'
```

**Comment by IamViditAgarwal** [comment]
> Try this code:
> 
> ```python
> import nbtools
> 
> @nbtools.build_ui(parameters={
>     "param_1": {
>         "type": "file",
>         "kinds": ["csv" , ".txt"]
>         }
>     })
> def file_up(param_1) :
>     return 'file is uploaded'
> ```
Cant we just wrap it up inside another function  ?? I was trying to wrap it up in function and call that function . WIll it not work. Bcz In that I m only getting error of function not defined

**Comment by tmtabor** [comment]
Try this. It works for me in Jupyter 5.7:

```python
import nbtools

def foo():
    @nbtools.build_ui(parameters={
        "param_1": {
            "type": "file",
            "kinds": ["csv" , ".txt"]
            }
        })
    def file_up(param_1) :
        return 'file is uploaded'
    
foo()
```

**Comment by IamViditAgarwal** [comment]
> Try this. It works for me in Jupyter 5.7:
> 
> ```python
> import nbtools
> 
> def foo():
>     @nbtools.build_ui(parameters={
>         "param_1": {
>             "type": "file",
>             "kinds": ["csv" , ".txt"]
>             }
>         })
>     def file_up(param_1) :
>         return 'file is uploaded'
>     
> foo()
> ```

I have tried ur code , but it didnot work for me ..
IN my system : Following are the package versions : 
jupyter-notebook : 5.5.0
jupyter : 4.4.0

I have also attached the screenshot of the error
![screenshot from 2018-12-06 14-41-40](https://user-images.githubusercontent.com/43881643/49575106-ee507c80-f967-11e8-9c58-0cec8ac19d8c.png)

**Comment by tmtabor** [comment]
Okay, I think I have a better idea now what you're trying to do with the code. In this case I think you're probably better off returning a UIBuilder object directly rather than using the decorator.

Try this:

```python
import nbtools

def foo():
    def file_up(param_1) :
        return 'file is uploaded'

    return nbtools.UIBuilder(file_up, parameters={
        "param_1": {
            "type": "file",
            "kinds": ["csv" , ".txt"]
        }
    })

foo()
```

**Comment by IamViditAgarwal** [comment]
> import nbtools def foo(): def file_up(param_1) : return 'file is uploaded' return nbtools.UIBuilder(file_up, parameters={ "param_1": { "type": "file", "kinds": ["csv" , ".txt"] } }) foo()

Still facing the same issue : 
![issue_nbtools](https://user-images.githubusercontent.com/43881643/49628440-24463d00-fa0a-11e8-9616-2683c1b29fb1.png)

**Comment by tmtabor** [comment]
Third time's a charm. I think I know what's going wrong for you. Try this:

```python
import nbtools

def file_up(param_1) :
    return 'file is uploaded'

def show_upload():
    return nbtools.UIBuilder(file_up, parameters={
        "param_1": {
            "type": "file",
            "kinds": ["csv" , ".txt"]
        }
    })

show_upload()
```

**Comment by IamViditAgarwal** [comment]
Wholaa , It is working this time now, **I will do some more test and will close the issue after it**..

Thanks for staying on this issue for so long..
Regards
Vidit
