### ISSUE TITLE
Download a FIle

### ISSUE THREAD

**Issue by IamViditAgarwal** [genepattern/nbtools#2]
I was wondering does nbtools provide something for file download also similar to file upload ?

**Comment by tmtabor** [comment]
NBTools supplies a file widget which includes upload functionality. Alternatively, you could implement your own upload or download tool. You can see how it [implements upload functionality by checking out the source of the widget](https://github.com/genepattern/nbtools/blob/master/nbtools/static/file.js) (looking for the function named `upload`).

**Comment by IamViditAgarwal** [comment]
Thanks.. I am closing this issue
