### ISSUE TITLE
nbtools not work in python2

### ISSUE THREAD

**Issue by IamViditAgarwal** [genepattern/nbtools#3]
HI , I have been using nbtool framework for python3. I want to use it for the python2 support also. 

`I have tried installing nbtools in python2 by this command : pip2 install nbtools` .
But when running any widget builder getting couple of errors for libraries that are in python3  like inspect.signature.

For some I have installed a backward compatbility like for  `inspect.signature I have installed funcsigs and use it`. But getting another errors like for '__qualname__' [ in __init__ method of Class UIBuilder on line ` self.name = custom_name or function_or_method.__qualname__`]

PS : Anyone can help me out this
THanks in advance
Vidit

**Comment by tmtabor** [comment]
Currently the package does not support Python 2, as Python's support for 2.7 ends in a little over a year.

**Comment by IamViditAgarwal** [comment]
Thanks
