### ISSUE TITLE
AttributeError in scRNAseq clustering notebook with nbtools 19.09

### ISSUE THREAD

**Issue by alex-wenzel** [genepattern/nbtools#4]
I am trying to run the single cell clustering notebook locally in `genepattern/genepattern-notebook:19.09.1`. When the first cell with a `UIBuilder` auto-runs, I get this error:

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/32204469/65568724-abb85a80-df0f-11e9-8554-0c7ee3f624ae.png">

The notebook runs fine on the public notebook server. I'm not sure what image version is running on the public server, but I did notice that my local image has `nbtools==19.09` and the production notebook as `nbtools==19.07.4`. 

Some light googling seems to indicate that otherwise nonsensical `AttributeErrors` can be caused by self-referential imports in some cases, and I did notice [this line](https://github.com/genepattern/nbtools/commit/d47c04227d56a5ea44e430506044bba69e0592c7#diff-d72b525a3bf7c01a6e9786fccdd28a4bR69) in a recent commit, maybe the issue is related to that?

**Comment by bahill** [comment]
Hi Alex, 

19.09 is still in beta and Thorin is working on a fix for this, coming out of the testing I've been doing this week.
If you can revert to 19.07.1 (that is what is running in the production workspace) it should work.
